/**
 * This file was automatically generated by fastify-extract-definitions.
 * DO NOT MODIFY IT BY HAND. Instead, modify the fastify routes schemas
 * and re-run project to regenerate this file.
 */

import {
  ContextConfigDefault,
  FastifyInstance,
  FastifyLoggerInstance,
  FastifyRequest,
  FastifySchema,
  FastifyTypeProvider,
  FastifyTypeProviderDefault,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerBase,
  RawServerDefault,
} from 'fastify';
import { FastifyReply } from 'fastify/types/reply';
import { RouteGenericInterface } from 'fastify/types/route';
import {
  FastifyRequestType,
  ResolveFastifyRequestType,
} from 'fastify/types/type-provider';

export type RouteHandlerMethod<
  RawServer extends RawServerBase = RawServerDefault,
  RawRequest extends RawRequestDefaultExpression<RawServer> = RawRequestDefaultExpression<RawServer>,
  RawReply extends RawReplyDefaultExpression<RawServer> = RawReplyDefaultExpression<RawServer>,
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault,
  SchemaCompiler extends FastifySchema = FastifySchema,
  TypeProvider extends FastifyTypeProvider = FastifyTypeProviderDefault,
  RequestType extends FastifyRequestType = ResolveFastifyRequestType<
    TypeProvider,
    SchemaCompiler,
    RouteGeneric
  >,
  Logger extends FastifyLoggerInstance = FastifyLoggerInstance
> = (
  this: FastifyInstance<RawServer, RawRequest, RawReply, Logger, TypeProvider>,
  request: FastifyRequest<
    RouteGeneric,
    RawServer,
    RawRequest,
    SchemaCompiler,
    TypeProvider,
    ContextConfig,
    Logger,
    RequestType
  >,
  reply: FastifyReply<
    RawServer,
    RawRequest,
    RawReply,
    RouteGeneric,
    ContextConfig,
    SchemaCompiler,
    TypeProvider,
    RouteGeneric['Reply']
  >
) => Promise<RouteGeneric['Reply']> | RouteGeneric['Reply'] | void;

export type Handler<
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault
> = RouteHandlerMethod<
  RawServerDefault,
  RawRequestDefaultExpression,
  RawReplyDefaultExpression,
  RouteGeneric,
  ContextConfig
>;

export type RootOptions = object;

export type HealthzGetReply = Status | Error;

export type PublicWTokenDashboardGetReply =
  | PublicWTokenDashboardGetReplyStatus200
  | PublicWTokenDashboardGetReplyStatus304
  | Error;

export type EnumsWorkerStatus = 'online' | 'offline' | 'inactive';

export type PublicWTokenDashboardGetReplyStatus304 = null;

export type SwaggerGet = object;

export type SwaggerJsonGet = object;

export type SwaggerStaticAllGet = object;

export type SwaggerStaticIndexhtmlGet = object;

export type SwaggerStaticSwaggerInitializerjsGet = object;

export type SwaggerYamlGet = object;

export type EnumsClient = 'web';

export type EnumsEnvironment = 'local' | 'staging' | 'production';

export type EnumsLocale = 'ru';

export type EnumsMode = 'production' | 'development' | 'test';

export type EnumsOrderDirection = 'asc' | 'desc';

export interface API {
  '*': {
    OPTIONS: RootOptions;
  };
  '/healthz': {
    GET: HealthzGet;
  };
  '/public/w/:token/dashboard': {
    GET: PublicWTokenDashboardGet;
  };
  '/swagger': {
    GET: SwaggerGet;
  };
  '/swagger/': {};
  '/swagger/json': {
    GET: SwaggerJsonGet;
  };
  '/swagger/static/*': {
    GET: SwaggerStaticAllGet;
  };
  '/swagger/static/index.html': {
    GET: SwaggerStaticIndexhtmlGet;
  };
  '/swagger/static/swagger-initializer.js': {
    GET: SwaggerStaticSwaggerInitializerjsGet;
  };
  '/swagger/yaml': {
    GET: SwaggerYamlGet;
  };
}

/**
 * Health check
 */
export interface HealthzGet {
  Reply: HealthzGetReply;
}

/**
 * Status response
 */
export interface Status {
  status: boolean;
}

/**
 * Error response
 */
export interface Error {
  error: string;
  message?: string;
}

/**
 * Get workers dashboard
 */
export interface PublicWTokenDashboardGet {
  Params: PublicWTokenDashboardGetParams;
  Reply: PublicWTokenDashboardGetReply;
}

export interface PublicWTokenDashboardGetParams {
  token: string;
}

export interface PublicWTokenDashboardGetReplyStatus200 {
  model: 'workers';
  item: WorkersDashboard;
}

/**
 * Workers dashboard model
 */
export interface WorkersDashboard {
  workers: {
    id: string;
    name: string;
    status: EnumsWorkerStatus;
    last_seen_at: string;
    hashrate_th: string;
  }[];
  agg: {
    online: number;
    offline: number;
    inactive: number;
    total_hashrate_th: string;
  };
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "enums".
 */
export interface Enums {
  client: EnumsClient;
  environment: EnumsEnvironment;
  locale: EnumsLocale;
  mode: EnumsMode;
  orderDirection: EnumsOrderDirection;
  workerStatus: EnumsWorkerStatus;
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "fragments".
 */
export interface Fragments {
  version: Version;
}

/**
 * Version fragment
 */
export interface Version {
  client: EnumsClient;
  environment: EnumsEnvironment;
  mode: EnumsMode;
  version: string;
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "statuses".
 */
export interface Statuses {
  error: Error;
  status: Status;
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Models {
  workers: WorkersDashboard;
}
